### ISSUE TITLE
python..py error: No module named 'requests'

### ISSUE THREAD

**Issue by sibernewf** [Lewington-pitsos/clip-download#1]
Hi Mate,
I have been following your tutorial, which is excellent.
I am stuck at 26:46 of the video.

I have downloaded the json from the clip site.
I have created the 'hd' directory in the clone of your repository.
I have run the: python install -r requirements.txt

Note I have only just downloaded your git repo, so it is the current version as of right now lol.

I have managed to install requirements as per your video.
but when I attempt to run 'python download.py'

I receive the following error:
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\repositories\clip-download\download.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Any ideas?

the first entry in my json file is:

[
  {
    "caption": "digital art drawing with smudge painting – photoshop tutorial",
    "url": "https://boxrean.com/wp-content/uploads/2021/05/thumbnail-455x300.jpg",
    "id": 2898557745,
    "similarity": "0.5602830052375793"
  },

... then it continues....

Ok, I managed to manually install requests by:
     python -m pip install requests

but now when I run download.py, it doesn't download images but it looks like the command is running (i.e. there is no longer a blinking cursor...)

**Comment by sibernewf** [comment]
it appears i am not very smart.  its working now.  my solution - I am ashamed to say was i forgot to run 'python download.py' - I forgot the python part.  oh the shame!

**Comment by natemac** [comment]
had the same issue, running 'python -m pip install requests' fixed it as well. should add to the read me
